#!/usr/bin/env bash
#
# A wizard — walks a human through the iOS spike run step by step.
# Generated by the /wizard skill for prototype/ios-app-spike.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser/Xcode/iPhone; this wizard tells you exactly what to do\n'
  printf '  and captures the probe results. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Spike run complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "results saved to $ENV_FILE:"
  if (( ${#WRITTEN_ENV[@]} )); then
    for k in "${WRITTEN_ENV[@]}"; do
      printf '  %s%s=%s%s\n' "$GREEN" "$k" "$(_existing "$k")" "$RESET"
    done
  fi
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n%s  Paste the values above (or the whole results.env) back to the agent.\n' "$DIM"
  printf '%s\n' "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# This spike's directory (wizard lives at spike/dataplane/wizard.sh)
SPIKE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SPIKE_DIR/results.env"
XCODE_PROJ="$SPIKE_DIR/ios/App/App.xcodeproj"

TOTAL_STAGES=7

banner "LocalTransfer 数据面 spike — 真机验证"

# ── Stage 1: 依赖 + cap sync ──────────────────────────────────────────────
stage "安装依赖并同步 www 到 iOS 壳"
say "需要 Node + npm（本仓库已有）。cap sync 会把 www/ 拷进 ios/App/App/public，并注册 SPM 依赖。"
step "在仓库根目录执行：cd spike/dataplane && npm install"
step "然后执行：npx cap sync ios"
if [[ -d "$SPIKE_DIR/ios/App/App/public" ]] && [[ -f "$SPIKE_DIR/ios/App/App/public/index.html" ]]; then
  say "  ✓ 检测到 www 已同步（ios/App/App/public/index.html 存在）。"
else
  warn "还没检测到 public/index.html —— 先跑 npx cap sync ios 再继续。"
fi
pause "npm install + cap sync 完成后按 Enter 继续"

# ── Stage 2: Xcode 打开工程 + 签名 ────────────────────────────────────────
stage "打开工程并配置签名"
open_url "file://$XCODE_PROJ"
say "如果链接没打开,手动打开:$XCODE_PROJ"
step "选中左侧 Target「App」→ 右侧 Signing & Capabilities(签名与功能)。"
step "勾选 Automatically manage signing → Team 选你的个人团队(免费个人账号即可,7 天有效)。"
step "确认 Bundle Identifier 保持 local.transfer.dataplane(或改成你自己的唯一值)。"
step "用数据线连接 iPhone → Xcode 顶部设备下拉选择你的 iPhone。"
pause "签名配置好、设备已选中后按 Enter 继续"

# ── Stage 3: 构建并运行 ───────────────────────────────────────────────────
stage "构建并运行(⌘R)"
step "Xcode 里按 ⌘R。首次构建会解析 SPM 依赖(capacitor-swift-pm,需要联网)。"
step "构建成功后 app 会自动装到 iPhone 并启动(黑屏白字 LT-Dataplane)。"
warn "若报错 'requires a development team' → 回 Stage 2 选 Team。"
warn "若报错其他编译错误 → 把 Xcode 报错原文发回给 agent。"
pause "app 在 iPhone 上启动后按 Enter 继续"

# ── Stage 4: 真机信任(仅首次)──────────────────────────────────────────────
stage "iPhone 信任开发者证书(仅首次)"
step "iPhone:设置 → 通用 → VPN 与设备管理 → 开发者 App → 找到你的 Apple ID → 点「信任」。"
step "回到 app(可能需要重开一次)。"
pause "信任完成后按 Enter 继续"

# ── Stage 5: 桌面 Chrome 腿 ───────────────────────────────────────────────
stage "桌面 Chrome 腿(对照组)"
step "在仓库根目录执行：cd spike/dataplane && node smoke/serve.mjs"
step "桌面 Chrome 打开 http://localhost:8080(页面与 app 内完全同一份)。"
warn "若桌面 Chrome 建连停在 connecting：很可能是本机代理/TUN(Clash 等)劫持了 WebRTC candidate —— 临时关掉代理/TUN 再试。"
pause "两端页面都打开后按 Enter 继续"

# ── Stage 6: 跑测试矩阵 ───────────────────────────────────────────────────
stage "跑建连测试矩阵 + 数据面测试"
say "两台设备(手机 app 与桌面 Chrome)在页面里填【同一个 4 位房间码】并「加入房间」。"
say "任一端点「发起连接」即可；对端自动应答。"
say "跑完一组后点「断开」或换新房间码跑下一组。"

say "【组 1】手机 app ↔ 桌面 Chrome："
step "1a 冷启动：不点「授权摄像头/麦克风」直接发起连接 → 记录能否建连、报错原文、是否弹权限窗。"
step "1b 先授权：点「授权摄像头/麦克风」→ 允许 → 再发起连接 → 记录能否建连与耗时。"
step "1c 建连成功后跑：往返延迟(×20)、吞吐(128 MiB)、观察 Xcode 内存仪表峰值。"
step "1d 后台探针：吞吐跑到一半时把 app 切到后台 5 秒再回来 → 记录对端日志是否出现「收包间隙」。"

say "【组 2】手机 app ↔ 手机 app(第二台 iPhone 或 iOS 模拟器；模拟器在 Xcode 里选)："
step "重复 1a-1d 的四步。"

ask WK_DEVICE         "iPhone 型号 + iOS 版本(如 iPhone 16 · iOS 18.5):"
ask CHROME_VER        "桌面 Chrome 版本:"
ask COLDA_OK          "1a 冷启动建连是否成功(y/n):"
ask COLDA_ERR         "1a 失败时的报错原文(无则留空):"
ask COLDA_PROMPT      "1a 是否自动弹出了权限弹窗(y/n):"
ask GRANT_OK          "1b 授权后建连是否成功(y/n):"
ask GRANT_MS          "1b 建连耗时(ms):"
ask LATENCY_MED       "延迟中位数(ms):"
ask TP_SEND           "吞吐·发送端(MB/s):"
ask TP_RECV           "吞吐·接收端(MB/s):"
ask MEM_PEAK          "峰值内存(app 侧,Xcode 内存仪表数字,如 350MB):"
ask BG_GAP            "后台探针:是否出现收包间隙(y/n):"
ask WK2WK             "组 2 是否测了(第二台/模拟器)(y/n):"
ask WK2WK_RESULT      "组 2 结论(如 'A 授权后可用,B 冷启动失败'):"
write_env WK_DEVICE     "$WK_DEVICE"
write_env CHROME_VER    "$CHROME_VER"
write_env COLDA_OK      "$COLDA_OK"
write_env COLDA_ERR     "$COLDA_ERR"
write_env COLDA_PROMPT  "$COLDA_PROMPT"
write_env GRANT_OK      "$GRANT_OK"
write_env GRANT_MS      "$GRANT_MS"
write_env LATENCY_MED   "$LATENCY_MED"
write_env TP_SEND       "$TP_SEND"
write_env TP_RECV       "$TP_RECV"
write_env MEM_PEAK      "$MEM_PEAK"
write_env BG_GAP        "$BG_GAP"
write_env WK2WK         "$WK2WK"
write_env WK2WK_RESULT  "$WK2WK_RESULT"

# ── Stage 7: 结论分支 ─────────────────────────────────────────────────────
stage "结论分支(判据)"
say "分支 A = 数据通道可用(任一授权路径建连成功 + 吞吐 ≥ ~30 MB/s)→ 原生只管发现+信令,传输/续传/OPFS 全复用。"
say "分支 B = 不可用(授权后仍失败/吞吐远低于 30)→ app↔app 原生 TCP 数据面,电脑腿顺延。"
ask BRANCH           "结论分支(A/B):"
ask TP_RATE_CONFIRM  "吞吐是否 ≥ 30 MB/s(y/n):"
write_env BRANCH          "$BRANCH"
write_env TP_RATE_CONFIRM "$TP_RATE_CONFIRM"
# ──────────────────────────────────────────────────────────────────────────

finish
